### ISSUE TITLE
Botão de pânico

### ISSUE THREAD

**Issue by celsoribeiro** [metaheur/teste#1]
ljansljvna sk akjsnjlanslnakjs  aks vljansvljnasknv aksjnvjansjkv ans v akjsvjnasjkv ak

**Comment by leomurta** [comment]
ndsjlkjsnv sd ksjndcklnsdcjns dcskjdnkjsnvlksdkvsdvs vlsjlksndcs dcksjdcjlsnd

**Comment by celsoribeiro** [comment]
sbkjsbkjbs dckbskdcnkjd
